plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.5-beta'
}

version = project.mod_version
group = 'dev.leo'

repositories {
    mavenLocal()
    maven { url = 'https://maven.neoforged.net/releases' }
}

base {
    archivesName = 'Active-Ragdolls'
}

neoForge {
    version = project.neo_version

    parchment {
        mappingsVersion = '2024.07.28'
        minecraftVersion = '1.21'
    }

    runs {
        client {
            client()
        }
        server {
            server()
        }
    }

    mods {
        "${project.mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

tasks.named('jar', Jar) {
    archiveFileName = "Active-Ragdolls-${project.minecraft_version}-${project.mod_version}.jar"
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}