modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="sableplayerragdoll"
version="1.21.1-0.7.5"
displayName="Active Ragdolls"
authors="Leo"
description="Active player and mob ragdoll physics mod."