modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="activeragdolls"
version="1.21.1-0.7.5"
displayName="Active Ragdolls Addon"
authors="Leo"
description="Active player and mob ragdoll physics addon mod."